import React, { useEffect, useState } from 'react';
import { UserType } from '../../types/user'; 
import { modalStyles } from './EditProfile.styles';

interface EditProfileModalProps {
  currentUser: UserType;
  isOpen: boolean;
  onClose: () => void;
  onSave: (updatedData: Partial<UserType>) => Promise<void>;
}

export const EditProfileModal: React.FC<EditProfileModalProps> = ({ currentUser, isOpen, onClose, onSave }) => {
  const [username, setUsername] = useState(currentUser.username);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string>('https://via.placeholder.com/150');

  // Sync local state when the modal opens or user data changes
  useEffect(() => {
    if (isOpen) {
      setUsername(currentUser.username);
      setSelectedFile(null); // Clear any previously selected file
      
      if (!currentUser.profileImageUrl) {
        setPreviewUrl('https://via.placeholder.com/150');
      } else if (typeof currentUser.profileImageUrl === 'string') {
        setPreviewUrl(currentUser.profileImageUrl);
      } else if (currentUser.profileImageUrl instanceof File) {
        setPreviewUrl(URL.createObjectURL(currentUser.profileImageUrl));
      }
    }
  }, [isOpen, currentUser]);

  if (!isOpen) return null;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelectedFile(file);
      
      // Prevent memory leaks by revoking the old preview URL if it was generated by the browser
      if (previewUrl.startsWith('blob:')) {
        URL.revokeObjectURL(previewUrl);
      }
      
      // Create and set the new preview URL immediately
      setPreviewUrl(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    await onSave({
      username,
      ...(selectedFile && { profileImage: selectedFile })
    });
    
    setIsSubmitting(false);
    onClose();
  };

  return (
    <div style={modalStyles.overlay}>
      <div style={modalStyles.modal}>
        <div style={modalStyles.header}>
          <h2 style={modalStyles.title}>Edit Details</h2>
          <button style={modalStyles.closeButton} onClick={onClose}>&times;</button>
        </div>

        <form onSubmit={handleSubmit} style={modalStyles.form}>
          
          {/* Image Preview Section */}
          <div style={modalStyles.previewContainer}>
            <img 
              src={previewUrl} 
              alt="Profile Preview" 
              style={modalStyles.imagePreview} 
            />
          </div>

          <div style={modalStyles.inputGroup}>
            <label style={modalStyles.label}>Change Profile Photo</label>
            <input 
              type="file" 
              accept="image/*" 
              onChange={handleFileChange} 
              style={modalStyles.fileInput}
            />
          </div>

          <div style={modalStyles.inputGroup}>
            <label style={modalStyles.label}>Username</label>
            <input 
              type="text" 
              value={username} 
              onChange={(e) => setUsername(e.target.value)} 
              required
              style={modalStyles.textInput}
            />
          </div>

          <button 
            type="submit" 
            disabled={isSubmitting} 
            style={{...modalStyles.submitButton, opacity: isSubmitting ? 0.7 : 1}}
          >
            {isSubmitting ? 'Saving...' : 'Save Changes'}
          </button>
        </form>
      </div>
    </div>
  );
};