import { Request, Response } from "express";
import User from "../models/userModel";
import { AuthRequest } from "../middlewares/authMiddleware";

export const getProfile = async (req: AuthRequest, res: Response) => {
  const user = await User.findById(req.userId).select("-password");
  if (!user) return res.status(404).json({ error: "User not found" });
  res.json(user);
};

// export const updateProfile = async (req: AuthRequest, res: Response) => {
//   const { username, profileImageUrl } = req.body;
//   const user = await User.findById(req.userId);
//   if (!user) return res.status(404).json({ error: "User not found" });

//   if (username) user.username = username;
//   if (profileImageUrl) user.profileImageUrl = profileImageUrl;
//   await user.save();

//   res.json(user);
// };

export const updateProfile = async (req: AuthRequest, res: Response) => {
  try {
    // Get the username from the parsed text fields
    const { username } = req.body;
    
    // Get the uploaded file object generated by Multer
    const imageFile = req.file; 

    const user = await User.findById(req.userId);
    if (!user) return res.status(404).json({ error: "User not found" });

    // Update the username if one was provided
    if (username) {
      user.username = username;
    }

    // Update the image if a new file was uploaded
    if (imageFile) {      
      // imageFile.path contains the URL (if using Cloudinary) or local path (if using disk storage)
      user.profileImageUrl = `/uploads/${imageFile.filename}`; 
    }

    await user.save();

    // Send back the updated user so the React frontend can update the UI instantly
    res.json(user);
    
  } catch (error) {
    console.error("Error updating profile:", error);
    res.status(500).json({ error: "Failed to update profile" });
  }
};

export const getUserById = async (req: Request, res: Response) => {
  try {
    // Uses req.params.id from the URL instead of the token
    const user = await User.findById(req.params.id).select("-password");
    if (!user) return res.status(404).json({ error: "User not found" });
    
    res.json(user);
  } catch (error) {
    res.status(500).json({ error: "Server error" });
  }
};